### ISSUE TITLE
[Traefik Pilot] Traefik Plugin Analyzer has detected a problem.

### ISSUE THREAD

**Issue by traefiker** [jgoodson/couch-proxyauth-middleware#1]
The plugin was not imported into Traefik Pilot.

Cause:
```
failed to run with Yaegi: plugin: failed to eval CreateConfig: 1:28: undefined: couch_proxyauth_middleware
```
Traefik Plugin Analyzer will restart when you will close this issue.

If you believe there is a problem with the Analyzer or this issue is the result of a false positive, please contact [us](https://community.containo.us/).

**Comment by jgoodson** [comment]
Attempted to address with https://github.com/jgoodson/couch-proxyauth-middleware/commit/3c1388de87c2a817e9839beb622a6ee9b31b8ae3
